### ISSUE TITLE
New skyux modern theme + sky 4 updates has full border radius on search button

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-lookup#103]
### Expected behavior
The search button only has border radius on the right side

### Actual behavior
The search button has border radius on all sides, looking out of place with the input field

### Steps to reproduce
Be on the latest version of sky-lookup and look at the search field. The styling is specifically coming from the new modern theme's border styling

### Severity
Cosmetic

### Impact
High - everywhere

**Comment by blackbaud-conorwright** [comment]
![image](https://user-images.githubusercontent.com/20093443/85408880-1c3de780-b533-11ea-8419-e13dfa1285a7.png)

**Comment by Blackbaud-PaulCrowder** [comment]
#124
