### ISSUE TITLE
Responsive search component expands below toolbar view controls

### ISSUE THREAD

**Issue by Blackbaud-CoreyArcher** [blackbaud/skyux-lookup#119]
### Expected behavior
When expanding a responsive `sky-search` component on a toolbar, The expanded search bar's controls should be visible over the rest of the items on the toolbar.

### Actual behavior
When expanding a responsive `sky-search` component on a `sky-toolbar` that contains a `sky-toolbar-view-actions` component with view controls, the view control elements appear above the expanded search bar controls, preventing the user from interacting with them, or closing the expanded toolbar.

### Severity
This can render the toolbar unusable, and in a mobile view with no way to trigger media breakpoints, is unrecoverable.

[AB#1551335](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1551335)

**Comment by Blackbaud-TrevorBurch** [comment]
![image (2)](https://user-images.githubusercontent.com/19909569/90150186-67b28c00-dd53-11ea-842c-59bb3aac061c.png)
