### ISSUE TITLE
Search control has gap in border between clear and search buttons

### ISSUE THREAD

**Issue by Blackbaud-BaradaDash** [blackbaud/skyux-lookup#121]
### Expected behavior
The search control should look like one continuous input control without the border breaking in-between.
### Actual behavior
When search text is typed in and enter is pressed, it introduces the clear button. Probably because button class has margin-right as 5px, this results in a break in the border between the clear button and search button.
### Steps to reproduce
![image](https://user-images.githubusercontent.com/26814775/90062063-b5ec6e80-dd04-11ea-99fd-4c1e4a51e8a4.png)

### Severity
Cosmetic
### Impact
Low

[AB#1551345](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1551345)

**Comment by Blackbaud-TrevorBurch** [comment]
This is being seen with the default theme and Sky UX Lookup versions `4.2.0` and `4.2.1`

**Comment by Blackbaud-BaradaDash** [comment]
This is a non-issue. Incidentally, custom css was overriding button class with ng-deep. Apologies for the confusion. Marking this issue as Closed.
