### ISSUE TITLE
New theme for Search input

### ISSUE THREAD

**Issue by blackbaud-BenWong** [blackbaud/skyux-lookup#124]
### Expected behavior
Search input should have the modern theme style when used in a modern theme SPA.

### Actual behavior
Rounded corners are applied to the icon but not the text field.
![image (23)](https://user-images.githubusercontent.com/23264858/91763594-d12ff880-eba3-11ea-82e2-f721ac95f1e0.png)

### Impact

[AB#1565741](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1565741)

**Comment by Blackbaud-PaulCrowder** [comment]
#134
