### ISSUE TITLE
Closing a modal while an autocomplete is showing, doesn't get rid of the autocomplete popover

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-lookup#132]
### Expected behavior
The autocomplete countries list goes away when the modal is closed.

### Actual behavior
the popover goes to the top left of the screen and remains

### Steps to reproduce
1. put a phone field in a modal
2. switch to country selector, and type in `unit`
3, press the escape key to close the modal
4. see that the popover remains in the top left corner

#### Edit: New Information 9/26/2020
1. put _any autocomplete_ in a modal
2. _type text which will show results_
3, press the escape key to close the modal
4. see that the popover remains in the top left corner

### Severity
doesn't block functionality and can be dismissed by clicking one of the countries. I'd say cosmetic

### Impact
Anywhere a phone field is in a modal. At least in our spa, all forms are in modals so it's heavy from our perspective.

#### Edit: New Information 9/26/2020
Affects anywhere an autocomplete is in a modal.

[AB#1566358](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1566358)

**Comment by Blackbaud-TrevorBurch** [comment]
Transferred this issue as this is an issue for all autocompletes and not just those within the phone field.

**Comment by Blackbaud-TrevorBurch** [comment]
https://stackblitz.com/edit/angular-ziskov

**Comment by harpal-singh1** [comment]
It's also happens without closing the modal, If I type in hurry and press tab its intermittent in this case but it happens (with server side data source).

**Comment by Blackbaud-TrevorBurch** [comment]
Closing as I tested this on https://host.nxt.blackbaud.com/contact/ today and this did not occur so this has most likely been fixed since it was filed indirectly. We can reopen if this is still an issue for someone.

https://stackblitz.com/edit/angular-ziskov-dfj72n?file=package.json <-- StackBlitz referenced in the GitHub issue but updated with new package versions.
