### ISSUE TITLE
Autocomplete should have a "clear" and "search" button

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-lookup#16]
The autocomplete component should look similarly to the search component, including an "x" button and a magnifying glass icon. The "x" button should clear the selected item and field, while the magnifying glass should trigger a search.

Both controls should NOT be accessible with the tab key.

**Comment by Blackbaud-AlexKingman** [comment]
Closing in favor of blackbaud/skyux-lookup#15
