### ISSUE TITLE
List-view-checklist search bar doesn't have same padding as other search bars.

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-lookup#19]
Compare vertical spacing between top and bottom of search bar vs other items in other bars:
![image.png](https://images.zenhubusercontent.com/5b719a493815ff014b1021bb/8b1b802e-6239-41ea-a6f0-c429fe67b140)

It appears there should be 7px top/bottom padding on everything, but the list-view-checkilst search bar has 5px.

This class seems to be the culprit:
```
.sky-search-dismiss-absolute {
  position: absolute;
  background-color: $sky-search-background-color;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  padding: $sky-padding-half;
}

```

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman where were you seeing the 7px? I just looked at quite a few of our toolbars and they all have 5px.

**Comment by Blackbaud-AlexKingman** [comment]
This was happening in the modal for Select Field. Since the issue was filed, the spacing seems to be fixed. It does not match the screen shot above any longer. Closing.
