### ISSUE TITLE
sky-autocomplete ngModel is Dirty and Touched immediately

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux-lookup#20]
### Expected behavior
Expect input field to behave as all others and not be dirty or touched until user interacts with it

### Actual behavior
The ngModel bound to the input field of a sky-autocomplete is immediately dirtied and touched

### Steps to reproduce
```
<sky-autocomplete [data]="[{ name: 'Red' },{ name: 'Blue' }]">
        <input skyAutocomplete id="my-autocomplete-template-driven" type="text" name="favoriteColor"
          [(ngModel)]="favoriteColor" #model="ngModel"/>{{model.dirty}}{{model.touched}}{{favoriteColor|json}}
      </sky-autocomplete>
```
render the html and note the values on screen for dirty and touched they will already be true

as a 'control' you can add the following html as see the difference

```
<input id="my-autocomplete-template-driven-control" type="text" name="favoriteColorText"
        [(ngModel)]="favoriteColorText" #textmodel="ngModel" />{{textmodel.dirty}}{{textmodel.touched}}
```
### Severity
low

### Impact
makes using this on data entry forms difficult since it leads to false positives in validation errors

**Comment by Blackbaud-StacyCarlos** [comment]
This could be fixed by setting lines 102-104 of the **autocomplete-input.directive.ts** to the following:

```
public writeValue(value: any): void {
    if (value) {
        this.value = value;
    }
}
```

**Comment by Blackbaud-BenCook** [comment]
@Blackbaud-AlexKingman I see this is in progress. Thank you for that! Do you know what an approximate time frame for this to make it into a release would be?
