### ISSUE TITLE
Option tokens/pills can extend over the lookup text area

### ISSUE THREAD

**Issue by Blackbaud-DavidKerr** [blackbaud/skyux-lookup#202]
### Actual behavior
![image](https://user-images.githubusercontent.com/12033707/125846224-47cd67ee-4d99-4ed1-a3a5-a4bfe72bb111.png)
When the token is wider than the text area, it begins to overlay and extend past the input field.
### Steps to reproduce
Choose an option that is wider than the text field. Slimming the browser window can help achieve this.
### Severity
Low
### Impact
Low

**Comment by Blackbaud-KerryCampbell** [comment]
Hi David, I'm going to close this out and move it to ADO.  If you could submit this through our new bug process [here ](https://dev.azure.com/blackbaud/Products/_workitems/create/Bug?templateId=762f6a46-de2a-49ee-b2c4-c3bb0ef60de0&ownerId=26bb0bf6-45ac-482d-b33e-02e252c297e3)in the future that will ensure that we see it.
