### ISSUE TITLE
Focus on the search button does not display left border

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-lookup#23]
### Expected behavior
When focus is on the `sky-search`'s button, it should have a border around the entire button to indicate that it has focus.

### Actual behavior
It only has borders on the top, right, and bottom.

### Steps to reproduce
Go to the [demo](https://developer.blackbaud.com/skyux/components/search) and click on the search button with the magnifying class icon.  Notice the incorrect focus border.

### Severity
Cosmetic

### Impact
Cosmetic

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.3`
