### ISSUE TITLE
Searching an empty string in sky-search component throws error

### ISSUE THREAD

**Issue by LeulBM** [blackbaud/skyux-lookup#33]
### Expected behavior
Searches involving an empty string will send the empty or undefined string to the specified function.
### Actual behavior
TypeError is thrown, stemming from the call to searchText.trim() in function applySearch
![image](https://user-images.githubusercontent.com/18249194/59934602-ea72dc00-9419-11e9-8d8c-aa2e9a5ad4db.png)

### Steps to reproduce
install @skyux/lookup v. 3.1.0
1. Create a <sky-search> component
2. Attempt to search an empty string
3. Observe error in the console

### Severity
Medium
### Impact
Low

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
