### ISSUE TITLE
Lookup/autocomplete results dropdown clipped when added to overflow container: Safari

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-lookup#39]
Open the following StackBlitz in Safari:
https://stackblitz.com/edit/angular-awdkkp

<img width="496" alt="Screen Shot 2019-10-11 at 10 45 48 AM" src="https://user-images.githubusercontent.com/12497062/66661056-50c37a80-ec14-11e9-83c5-c1e40de98315.png">

**Comment by Blackbaud-AlexKingman** [comment]
This particular issue stems from placing autocomplete in a container with `position: relative`, which in this case, is the modal. This is a underlying issue with the popover component. We are looking into building an overlay service that will avoid these issues in the future.

In the meantime, this should suffice as a workaround - place this into the `.scss` that conains the modal:
```
::ng-deep .sky-modal-content {
  z-index: auto !important;
}
```
