### ISSUE TITLE
Can't require lookups in template driven forms

### ISSUE THREAD

**Issue by Blackbaud-ErikaMcVey** [blackbaud/skyux-lookup#40]
### Expected behavior
You should be able to set `required` on the input so that it requires a value for a SKY lookup.

### Actual behavior
The consumer does not have access to to the input so they cannot set `required`. You can put `required` on the `sky-lookup` element, but it doesn't have the right functionality--the lookup is autofocused and in an error state.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.3.2`
