### ISSUE TITLE
Can't see autocomplete search when without padding

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-lookup#42]
### Expected behavior

Search results show below autocomplete so you can see what you're typing (note padding left and right at 1px)

![image](https://user-images.githubusercontent.com/5076129/67304975-46c63500-f4ba-11e9-8134-35d5fc30bda0.png)

### Actual behavior

Search results show on top of typing - note padding at 0px (doesn't matter if left or right padding of 1px)

![image](https://user-images.githubusercontent.com/5076129/67304968-4037bd80-f4ba-11e9-9fc6-b9f1f6a028c8.png)

### Steps to reproduce

Use autocomplete component w/ 0 padding (i.e., in a plain div, not in a `sky-form-control` class)

### Severity

High

### Impact

All users of sky-autocomplete

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-IsaacAggrey Which browser are you seeing this in? I couldn't reproduce in StackBlitz.
https://developer.blackbaud.com/skyux/components/autocomplete

**Comment by Blackbaud-IsaacAggrey** [comment]
I don't seem to be running into this anymore, so I'll close for now.
