### ISSUE TITLE
Autocomplete shows empty dropdown when no results returned

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-lookup#43]
### Expected behavior

When the autocomplete returns no results it used to show nothing below the component. Ideally we would love to have a message that indicated that no results were returned.

### Actual behavior

After upgrading to popovers 3.4.0 whenever the autocomplete returns no results then an empty dropdown is shown below.

### Steps to reproduce

1. Create an autocomplete component
2. Use 3.4.0 of the popovers package
3. Search for something with no results

Can be reproduced here: https://stackblitz.com/run?file=src/app/demo/autocomplete-demo.component.html

**Comment by Blackbaud-SteveBrush** [comment]
We should fix the bug, but show a message "No matching items found" if no results are found.
