### ISSUE TITLE
3.2.1 search bar min-width too long for container

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-lookup#56]
### Expected behavior
Search bar's min width does not exceed the width of it's container nor the window itself

### Actual behavior
Search bar gets a min-width that is calculated somewhere and produces wildly different values for 2 search bars side by side. 
Provided are 2 screenshots from our spa. One is using 3.2.0 and the other is using 3.2.1. Note the left search bar appears unaffected and looks exactly the same, however, the right one grows past the page. 
Upon looking at the elements and their styling, the issue appeared to be with the div that contains the classes "sky-search-input-container sky-input-group ng-trigger ng-trigger-inputState". It also contained inline styling which gave the right search bar a min-width of 779px. Meanwhile the left search bar's div with the same classes only had a min-width of 15px. 
Furthermore, the right search bar's min width also appears to change based on the window's total width while the left one stays at 15 regardless of window size.

3.2.0
<img width="1509" alt="3 2 0_lookup_issue" src="https://user-images.githubusercontent.com/7572597/76255194-cb241500-621b-11ea-8dae-78f69ad08abd.png">

3.2.1
<img width="1548" alt="3 2 1_lookup_issue" src="https://user-images.githubusercontent.com/7572597/76255196-cd866f00-621b-11ea-8fe5-2cdab43b311a.png">

### Steps to reproduce
Have 2 sky columns in a sky-fluid-grid ([example](https://blackbaud.visualstudio.com/Products/_git/skyux-spa-workflows?path=%2Fsrc%2Fapp%2Fworkcenter%2Fworkflow-repeaters-container%2Fworkflow-repeaters-container.component.html))
Create a component with a sky-repeater and a sky-search bar ([example](https://blackbaud.visualstudio.com/Products/_git/skyux-spa-workflows?path=%2Fsrc%2Fapp%2Fworkcenter%2Factive-workflow-repeater%2Factive-workflow-repeater.component.html))
Wrap the sky-search in a div and give it a style class where the width is set to 50% (aka the search bar will only take up half the space of the repeater component and each repeater component will only take ~50% of the screen entirely
Upgrade to sky-lookup 3.2.1. The left search bar behaves as expected. The right search bar does not and gets a width that extends just past the page. 

### Severity
Low/Medium as this really doesn't have a massive impact on functionality but it does make for a very odd UX

### Impact
Low again as this doesn't impact functionality but only aesthetics

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.3.2`
