### ISSUE TITLE
Consider including option to limit Countries returned

### ISSUE THREAD

**Issue by blackbaud-elizabethsmith** [blackbaud/skyux-lookup#81]
### Feature request
In order to support restricted Country selection use cases, it would be helpful to support the `onlyCountries` and `excludeCountries` options provided by the `intl-tel-input` library.  Example of `onlyCountries` available [here](https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/only-countries-europe.html).

**Comment by Blackbaud-SteveBrush** [comment]
The design team feels that this change would be detrimental to the user experience; if they type a country name and it doesn't show in the autocomplete, it may confuse the user if the country doesn't show up, e.g. "No country found.".

**Comment by Blackbaud-ToddRoberts** [comment]
Reopening after talking to RE designer. This is blocking their conversion to SKY 3, alternative is to use an html select which would be a much worse user experience.

**Comment by Blackbaud-AlexKingman** [comment]
Available in @skyux/lookup 3.6.0
