### ISSUE TITLE
Country field shows Chrome autocomplete as if it's a country field

### ISSUE THREAD

**Issue by jeffbdye** [blackbaud/skyux-lookup#93]
### Expected behavior
No browser autocomplete is shown and the component's autocomplete is displayed

### Actual behavior
Chrome's country autocomplete is displayed in place of the component's autocomplete, and clicking on the browser autocomplete causes an error to be printed to the console: ERROR TypeError: Cannot read property 'toLowerCase' of undefined.

### Steps to reproduce
Chrome 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable), Windows 10
https://host.nxt.blackbaud.com/person/?svcid=faith&envid=t-U0v9e508A0uWwRqTJgYdBw > Add person > contact information (vertical tab) > click into the country field component with your user having form autofill information present.

### Severity
Blocks the actual use of the component until the user hits escape to dismiss the browser autocomplete, which can also cause issues with the keyboard interactions when trying to select a country when the component autocomplete shows (up/down arrow).

### Impact
Doesn't seem to affect all uses of the country-field, it's likely specific to how the containing form is set up and how chrome tries very hard to ensure autocomplete is shown despite form configuration.

**Comment by jeffbdye** [comment]
Image of chrome autocomplete showing up below the component: 
![image](https://user-images.githubusercontent.com/4132425/82226494-8f30be80-98f4-11ea-964a-4d08364ff01e.png)

**Comment by jeffbdye** [comment]
According to @Blackbaud-AlexKingman , it might require having pre-existing autofill information with "United States" specifically.

**Comment by Blackbaud-AlexKingman** [comment]
Looks like a known bug with chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=914451&can=2&q=Autofill%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by Blackbaud-AlexKingman** [comment]
Available in @skyux/lookup 3.6.0.
