### ISSUE TITLE
Autocomplete dropdown list does not appear in mobile firefox

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [blackbaud/skyux-lookup#98]
### Expected behavior
When entering text in an autocomplete control, a dropdown should appear with items which match the text.

### Actual behavior
Text can be entered but no dropdown appears.

### Steps to reproduce
Using mobile Firefox on android, attempt to use any of the autocomplete controls in the docs: https://developer.blackbaud.com/skyux/components/autocomplete

Duplicated in Android 8.0.0, Firefox 68.9.0.

### Severity
Low

### Impact
Controls which make use of the autocomplete component will not work.  Users can switch to mobile Chrome as a workaround.

**Comment by Blackbaud-DanMiller** [comment]
hey Stew is this still an issue?

**Comment by Blackbaud-StewartStephens** [comment]
I am still able to reproduce this using the demo on the autocomplete documentation page, Android 8.0.0, Firefox 68.11.0.  My phone is pretty old so maybe it's an Android version issue?  I'm not sure if there's a way to use mobile Firefox through Browserstack.
